### ISSUE TITLE
StreamApp Resources Are Cleaned Up Only on JVM Termination

### ISSUE THREAD

**Issue by ChristopherDavenport** [functional-streams-for-scala/fs2#1075]
StreamApp resources are not cleaned on interruption and restoration of an sbt-command prompt only on JVM termination.

Here is a piece of code that replicates this behavior.

```scala
import cats.effect.IO
import fs2.async.immutable.Signal
import fs2.{Stream, StreamApp}
import scala.concurrent.ExecutionContext.Implicits.global

object fs2NativeStreamBrokenInfinite extends StreamApp[IO] {
  def  serverBehaviorWeWant(string: String, terminated: Signal[IO, Boolean]): Stream[IO, StreamApp.ExitCode] = Stream.bracket(IO(println(s"Started $string")))(
    using => terminated.discrete.takeWhile(_ == false).drain ++ Stream.emit(StreamApp.ExitCode(0)).covary[IO] ,
    release => IO(println(s"Release $string"))
  )
  def stream(args: List[String], requestShutdown: IO[Unit]) =
    for {
      exit <- Stream.eval(fs2.async.signalOf[IO, Boolean](false))
      out <- serverBehaviorWeWant("Stream1", exit)
        .concurrently(serverBehaviorWeWant("Stream2", exit))
    } yield out
}
```

[Repo Of Similar Examples](https://github.com/davenport-scala/concurrentlyfs2) - Any That Are Labelled With Broken show this behavior. 

Steps To Reproduce - 
1. Clone The ConcurrentlyFs2 Or The Above Snipped - Import in `build.sbt` -  `cancellable in Scope.Global := true`
2. Call `sbt` directly initially
3. Call `run` and select an application
4. Once The Stream Has Started Cancel With Ctrl-C
5. You will reach the sbt prompt again and resources will not have been released.
6. Calling `exit` will trigger resource release of all streams for this jvm

Luckily `sbt-revolver` works through a forked jvm so is unaffected by this problem. However would be nice to be able to work within the same sbt session. Let me know if I can help in any way.

**Comment by avakhrenev** [comment]
This is maybe an issue with sbt, how does it actually interrupt a working program?

I usually interrupt my app by hitting enter:
```scala
(io.readInputStream[IO](IO(System.in), 32, false)
  .takeWhile(_ != '\n') //read System.in to the end
  .drain
  .onFinalize(IO(println("Exiting...")) *> requestShutdown) mergeHaltBoth <your_stream>
```
Also in `build.sbt`
```scala
run / connectInput := true
```

**Comment by mpilquist** [comment]
When running SBT in this configuration (`fork := false, cancelable := true`), SBT simply shuts down the thread pool used for the task but doesn't signal anything to the running main function. For example, try running the following program with the above settings and then canceling via CTRL-C:

```scala
object A2 {
  def main(args: Array[String]): Unit = {
    val f = Future { 
      try { 
        println("Sleeping")
        Thread.sleep(20L * 1000L)
        println("Finished sleeping")
      } catch { 
        case t: Throwable =>
          println("Exception in future thread")
          t.printStackTrace
      }
    }
    try {
      Await.result(f, 1.minute)
      println("Main done waiting")
    } catch {
      case t: Throwable =>
        println("Exception in main thread")
        t.printStackTrace
    }
  }
}
```

You'll see the cancelation occur in SBT but you'll see that the thread that invoked `main` is *not* interrupted and the program continues to run until completion.

If you run with SBT debug logging, you can see there's no attempt to interrupt the thread executing `main` -- rather, the only output after `CTRL-C` is a rejected execution of a task to an SBT internal thread pool (likely the pool associated with the task).

So ultimately this appears to be an SBT limitation or bug. However, I noticed that the `main` in `StreamApp` doesn't handle interruption. That is, if an exception is thrown from `unsafeRunSync`, because the main thread is interrupted, I think we should consider requesting a stream shutdown (similar to what occurs from the JVM shutdown hook). There's a bit of an issue with the way that code is currently laid out though, as `main` doesn't have access to the signals needed to request a shutdown.

Anyway, I'm going to move this to post-0.10 final unless someone objects.

**Comment by pchlupacek** [comment]
@mpilquist fine with that. I think the design of StreamApp need indeed review. Is ok to do this post 0.10 hence this won't affect that much refactoring. In fact, just for consideration, not sure if StreamApp should not be in something like fs2-goodies, fs2-util or similar.

**Comment by pchlupacek** [comment]
Hence StreamApp is done the may be closed?
