### ISSUE TITLE
Import guide docs

### ISSUE THREAD

**Issue by benhutchison** [functional-streams-for-scala/fs2#1119]
Please include a section in the overview detailing the imports needed to use fs2, and any options/variants.

**Comment by Daenyth** [comment]
Is there anything to cover specific to fs2? In my own project I've never needed anything but the fs2 named types and then the various `cats` imports, and even that sparingly because most aren't super useful - really I only see `>>` for some `Pull` based operations

**Comment by djspiewak** [comment]
Shims-related imports are slightly tricky and seem to come up pretty often (due to the still-ubiquitous `Task`). These imports are tricky specifically because shims will normally materialize a `Monad[Task]`, but fs2 needs an `Effect[Task]` to operate, which then becomes ambiguous. I'm working on making this situation less tricky, but it's something to think about for now.

**Comment by benhutchison** [comment]
It doesn't need to be fancy. Just a couple of sentences. 

Just be aware that if you're a user coming new to the project, and you dont know the codebase, it is not at all "self-evident" what the intended imports are. Many scala projects only work as advertised with imports just right, so it would be good to specify early on what they are.

**Comment by mpilquist** [comment]
We could add this to the [FAQ](docs/src/faq.md)

**Comment by Daenyth** [comment]
I'm closing this for now since there's not a clear action. At this point in time, fs2 doesn't require any real imports aside from the types you mention - implicits and syntax etc, are provided in other libraries.

If someone has an example of what you'd like to see, please comment and we can reopen
