### ISSUE TITLE
`zip` and `zipWith` can cause an exception `Fail to find scope for next step`

### ISSUE THREAD

**Issue by ashlux** [functional-streams-for-scala/fs2#1120]
Example code and output:

```scala
import fs2._
import cats.effect._

val rangeStream = Stream.emits((0 to 3).toList).covary[IO]

val test = rangeStream.zip(rangeStream).attempt

test.compile.toList.unsafeRunSync()

// As expected, results in a list of 4 items: (0,0), (1,1), (2,2), (3,3)
// List[Either[Throwable,(Int, Int)]] = List(Right((0,0)), Right((1,1)), Right((2,2)), Right((3,3)))

test.map(identity).compile.toList.unsafeRunSync()

// Unexpectedly results in a list of 5 items including the error "Fail to find scope for next step"
// res1: List[Either[Throwable,(Int, Int)]] = List(Right((0,0)), Right((1,1)), Right((2,2)), Right((3,3)),
//         Left(java.lang.Throwable: Fail to find scope for next step: current: Token(6ba44bb0), step: Step(FreeC.Pure(()),Some(Token(41ee566c)))))
```

Expected output:

Both runs should result in a list of 4 elements: (0,0), (1,1), (2,2), (3,3). The only difference between the two is the use of `map(identity)`.

This only affects v0.10.3 (the problem does not appear in v0.10.2).

**Comment by AdamChlupacek** [comment]
The issue here is that attempt introduces scope. Which then is closed once either side of the zip finishes. But as both sides of the zip require said scope, once the other side is trying to get more data it requires the scope, but the scope is already closed and thus does not exist in the hierarchy.  

on v0.10.2 you will not be seeing an exception as `StepLeg` is defined with the scope in it already. But if there are any acquired resources they will be released. 

We probably need to lease the resources of the parent scope when we are creating `StepLeg`.
Will get a fix together today.

**Comment by AdamChlupacek** [comment]
On second thought, disregard all I just said, it may be something completely different, I will still get it fixed today. Thanks for the repro, it will make it easy to track down.
