### ISSUE TITLE
Memory leak with `groupWithin`

### ISSUE THREAD

**Issue by ImNotMyself** [functional-streams-for-scala/fs2#1303]
Hi all, I have observed a memory leak problem in my long-lived stream application.
After doing various experiments, I located the `groupWithin`
My sample:
```scala
Stream.eval(IO.never).covary[IO]
.groupWithin(Int.MaxValue, 1 millis)
.compile.drain.unsafeRunSync()
```
YourKit profiling(the old gen keeps growing and OutOfMemery finally):
![img_20181101_183624](https://user-images.githubusercontent.com/2851917/47847277-accb2f80-de05-11e8-8e5d-fda07a094938.jpg)

I am using this function to perform a time windowing in my stream. Is there any workaround in case the groupWithin is leaking ?
Kindly correct me if anything I missed.

**Comment by SystemFw** [comment]
Were you able to notice if any classes end up dominating the memory footprint?

**Comment by ImNotMyself** [comment]
I run the sample code above for 2min (old gen grows 5.4M -> 41M) and YourKit as below:
![img_20181101_212607](https://user-images.githubusercontent.com/2851917/47854724-726d8c80-de1d-11e8-8d31-e82b3cb65c10.jpg)
(apologize for the low resolution pic, since I do not have YourKit personally. The test is performed in my company laptop which blocked the upload access to github)

**Comment by mpilquist** [comment]
@systemfw I think the leak is in starting new timeouts without cancelling old ones here: https://github.com/functional-streams-for-scala/fs2/blob/9a4074df5763341b82828c02d6eb9db5c5c260c9/core/shared/src/main/scala/fs2/Stream.scala#L1148

**Comment by SystemFw** [comment]
oh, still had not time to have a look :(
I thought using the synchronous queue would prevent that, but perhaps they are just piling up whilst they're blocked on the queue (as opposed to the queue growing)

**Comment by SystemFw** [comment]
> but these finalizers accumulate over time.

Wow, interesting

> brackets the timeout to ensure it's later cancelled but these finalizers accumulate over time.

See, but my implementation doesn't rely on canceling timeouts, it makes them into no-ops by using a version number

**Comment by SystemFw** [comment]
So I wonder what happens by just removing `supervise`, because tbh I had only added it for syntactic convenience, my initial implementation only `start`ed.  it didn't even cross my mind that those finalisers could cause a leak.

**Comment by SystemFw** [comment]
Setting up something in MemorySanityChecks to verify this

**Comment by SystemFw** [comment]
@mpilquist any chance you can post your new code in a copy-pasteable format? I'd like to compare the memory profile with the thing I have

**Comment by SystemFw** [comment]
actually never mind I can work it out from the diff

**Comment by SystemFw** [comment]
Ok just replacing `supervise` with `eval( start)` has the same memory profile of your solution @mpilquist.
We need to think about the resource safety implications. 
Correctness does not depend on canceling an outstanding timeout, but if the stream gets interrupted we do leak a task that will sleep and try to enqueue on the queue.
Perhaps we could have a Ref to store the finaliser? They don't need to accumulate (I think) since only the outstanding one is relevant, which would avoid the leak that `supervise` introduces. WDYT?

**Comment by pchlupacek** [comment]
It sort of bothers me as well, that we do not cancel the `F` and leave them dangling around, for example re the last issue with PubSub and dequeue. 
I think interrupt shall cancel the task, and I am surprised it does not hence we Concurrent.race them, and that shall always cancel the loser shouldn't it ?

**Comment by SystemFw** [comment]
Currently trying to write another memory sanity test to check whether just replacing `supervise` with `start` will work, or whatever we would leak outstanding timeouts. 
Fairly tricky cause I think we can only leak one, so I'd have to repeatedly interrupt the Stream before the timeout gets enqueued and see what happens (I'm expecting a slower leak, but it should still leak)

**Comment by SystemFw** [comment]
so as expected, just removing `supervise` causes a very slow leak as things accumulate on the scheduledThreadPool. 
I'm trying to modify @mpilquist version so that the `cancel` finaliser is stored in a Ref, and `newTimeout` `getAndSet`s and cancels the old one. I then add one finaliser to the final stream which cancels the finaliser stored in the Ref in case of interruption, but I'm not sure this is enough to guarantee safety, and I can't completely shake the feeling that I'm doing Scope poorly. Will open a WIP PR for comments.
