### ISSUE TITLE
parEvalMap/parEvalUnOrdered slower than evalMap

### ISSUE THREAD

**Issue by regis-leray** [functional-streams-for-scala/fs2#1572]
Here my snippet of code

```scala
import java.util.concurrent.TimeUnit
import cats.effect.{ContextShift, IO}

object StreamPerfTest extends App {
  def timer(start: Long = System.nanoTime()): Long => String = { end =>
    val interval = end - start

    val min: Long = TimeUnit.NANOSECONDS.toMinutes(interval) % 60
    val sec: Long = TimeUnit.NANOSECONDS.toSeconds(interval) % 60
    val ms: Long = TimeUnit.NANOSECONDS.toMillis(interval) % 1000

    "%02d min %02d sec %03d ms".format(min, sec, ms)
  }

  def seqExec() = {
    val s = fs2.Stream.emits(0 to 50000).covary[IO].evalMap(i => IO(i + 2)).compile.drain

    val clock = timer()
    s.unsafeRunSync()
    println(clock(System.nanoTime()))
  }

  seqExec() // print 00 min 00 sec 149 ms


  def parExec() = {
    implicit val cs: ContextShift[IO] = IO.contextShift(scala.concurrent.ExecutionContext.Implicits.global)

    val s = fs2.Stream.emits(0 to 50000).covary[IO].parEvalMapUnordered(2)(i => IO(i + 2)).compile.drain

    val clock = timer()
    s.unsafeRunSync()
    println(clock(System.nanoTime()))
  }

  parExec() // print 00 min 03 sec 841 ms
}
```

From the documentation parEvalMap should run in parallel, so i was expecting to have my execution time decreasing not the inverse. I am doing something wrong ?

im using `fs2.core:1.0.5`, `cats-effects:1.3.1` with scala 2_12 and jdk-8 same problem with openjdk-11

**Comment by regis-leray** [comment]
Thread context shifting it is the main latency / bottleneck in this use case ?

**Comment by regis-leray** [comment]
```scala
val s = fs2.Stream.emits(0 to 500000)
      .covary[IO]
      .chunkLimit(1000)
      .map(cks => fs2.Stream.fromIterator[IO, Int](cks.iterator))
      .parEvalMap(6)(
        _.evalMap(i => IO(i + 2)).compile.drain
      )
      .compile
      .drain

    val clock = timer()
    s.unsafeRunSync()
    println(clock(System.nanoTime()))
```
this will improve dramatically the performance, in this use case. But i made some test with some real IO effect and i see big improvement

**Comment by SystemFw** [comment]
you can use `Stream.chunk` instead of going through `iterator`. In any case, the computations run _concurrently_, not necessarily in parallel, so for pure workloads such as these is not a given that you will see an improvement at all, and you are also dealing with overhead for several things that are needed in the general case (interruption, resource safety, switching, and so on).
It should be more convenient with a real IO with sends things to the network, sleeps and so on.
It almost boils down to the difference between concurrency and parallelism basically.

-----

As a separate point, the performance of `parEvalMap` can definitely be improved, you can see there are a few issues in the issue tracker already

**Comment by regis-leray** [comment]
@SystemFw this is exactly what i experiment, with real IO computation `you will see an improvement at all, and you are also dealing with overhead for several things that are needed in the general case (interruption, resource safety, switching, and so on).`

thanks a lot for your feedback really appreciated.
