### ISSUE TITLE
Semantics of njoin differs from semantics of join (in a wrong way)

### ISSUE THREAD

**Issue by dcsobral** [functional-streams-for-scala/fs2#274]
There's a difference between (scalaz) `join` and `njoin` when it comes to when a process is completed. The process that emits processes will be terminated before them with `njoin`, whereas it will terminated afterwards with `join`.

The documentation is silent on this, but the semantics of `join` seems preferable (and less surprising) to me.

Here's a reproduction:

    import scalaz._
    import Scalaz.{merge => _, _}
    import scalaz.concurrent._
    import scalaz.stream._
    import scala.concurrent.duration._
 
    implicit val defaultScheduler = scalaz.stream.DefaultScheduler
 
    val flag = async.signal[Boolean]
    val reset = Process.eval(flag set true).drain
    val sleep = Process sleep 50.millis
    val check = Process eval flag.get
    val completeEmitAll = Process.eval(flag set false).drain
    val emitAll: Process[Task, Process[Task, Boolean]] = Process(reset, sleep, check) onComplete completeEmitAll
 
    val test = for {
      join   <- emitAll.join.runLast
      mergeN <- merge.mergeN(emitAll).runLast
    } yield (join exists identity, mergeN exists identity)
 
    val (join, mergeN) = test.run 
 
    assert(join)
    assert(mergeN) // fails!

**Comment by djspiewak** [comment]
A very interesting sidebar here is that this issue with `onComplete` temporal sequencing results in `njoin` breaking the monadic associativity laws!  This isn't *strictly* an issue, since `njoin` doesn't directly make any pretensions to be `join`, but still it's interesting.

To be clear about what I mean:

```
m >>= (\x -> f x >>= g) = (m >>= f) >>= g
```

The above is of course the law of associativity for monads.  This holds for `>>=`, and by extension, `join`.  It's a very helpful thing to assume.  However, it simply does not hold in the following arrangement (assume `nbind` is defined in terms of `njoin` and `point`):

```
m nbind (\x -> f x >>= g) = (m nbind f) >>= g
```

If `m` has an `onComplete` which performs effects that are observable by the actions in the results of `g`, then the above identity will not hold.  In general, the left side will work (since it sequences `g` *inside* the `njoin`) while the right side will not.

Again, `njoin` certainly makes no pretensions (other than the name and type signature) of being monadic, but associativity is still a very natural property to *assume*.  It certainly was very surprising when we ran into the fact that it doesn't hold, and the code which shuffles the association of the binds still looks very weird to me.

**Comment by runarorama** [comment]
Is there a good reason it doesn't hold?

**Comment by djspiewak** [comment]
> Is there a good reason it doesn't hold?

Horror?

Seriously though, it's a problem with the underlying `Process

**Comment by pchiusano** [comment]
Going to close this. The new design runs finalizers in LIFO / innermost-first order, as you would expect. But we still need tests of this, created #535 to track.
