### ISSUE TITLE
BundleVersion is inconsistent

### ISSUE THREAD

**Issue by elyast** [functional-streams-for-scala/fs2#286]
Hi,

I noticed that bundleVersion is inconsistent, e.g.
```
scalaz-stream for scalaz 7.0 is 0.6
scalaz-stream for scalaz 7.1 is 0.0.0.6a
```
This is problematic since in OSGi only first 3 numbers are significant, which means version 0.0.0.5a and 0.0.0.6a is essentially 0.0.0 and cannot be use to scope version in import-package directive.

My suggestion would be to use following scheme:
```
0.6.0.a    for scalaz 7.1
0.6          for scalaz 7.0
```

Let me know what do you think

**Comment by pchiusano** [comment]
I am not sure what the current status on this is. +1 for changing the build script. @mpilquist or @elyast please go for it.

**Comment by williamsonm** [comment]
It doesn't seem like this is still an issue, since you're no longer building against multiple versions of scalaz and won't be releasing versions named 0.6, 0.6a, etc., right?  

I've added back OSGi support to the build, though, since it was dropped in the redesign, and can submit a pull request if you want.  This implementation doesn't use the BND range macro.

https://github.com/williamsonm/fs2/commit/5483daecfd35a2c97158a0d2a6525aba644f785f

**Comment by mpilquist** [comment]
@williamsonm A PR for 0.9 which adds back OSGi support would be much appreciated. Avoiding the BND range macro sounds good too. If you decide to open a PR, could you add OSGi headers for the fs2-io module too?
