### ISSUE TITLE
Provide easy way to traverse stream externally, eg Process[Task,A] => Iterator[A] and Proces1[I,O] => ...

### ISSUE THREAD

**Issue by florianverhein** [functional-streams-for-scala/fs2#323]
In order to integrate with external APIs or frameworks, it's best to allow Process to be driven externally (rather than e.g. adopt a blocking queue approach). `Iterator[A]` is a commonly used elsewhere, so is convenient.   

Useful conversions:
1. `Process[Task, A] => (Iterator[A], () => Unit)` where `() => Unit` is optional if the iterator is fully consumed, otherwise closes resources etc. 
2. `Process1[I,O] => (Iterator[I] => Iterator[O])` (no close required here right?)
3. `Process[Nothing, A] => Iterator[A]` 

Example use cases: Apache Spark integration. The first can be used to stream directly into an RDD via `flatMap`, as Iterator is a TraversableOnce (I do this and it works well). The second could be used to stream over an existing RDD via `RDD.mapPartitions` (I plan to do this). There are analogous cases in Scalding. 

Currently, it's possible to do 1. with the toTask trick (e.g. https://gist.github.com/florianverhein/2ed965bde7324cb73325) though @djspiewak mentioned this may be removed from the API. 

Please see discussion in #46 for background.

Ping @richardhundt

Edit: added 3.

**Comment by djspiewak** [comment]
There would certainly be no need for a close in **2**.  **1** is obviously an unsafe conversion, so we wouldn't want to just throw it on `Process`.  Any thoughts as to where this should go?

**Comment by florianverhein** [comment]
Sorry for late reply. No idea where it would live... Perhaps so that you would have to `import scalaz.stream.UnsafeConversions._` or similar?

**Comment by florianverhein** [comment]
Noticed you self assigned this @djspiewak, have you given **2** a go?

**Comment by pchlupacek** [comment]
@florianverhein can you please show example where we really need that combinator? Just for me to see if we don't have other option. I understood InputStream, because you have java api's (like java.mail) that take InputStream. Not sure on iterator though. 

I am not totally convinced if this has to live in core library, but perhaps I am just wrong. 

Thanks.

**Comment by florianverhein** [comment]
Sure @pchlupacek. E.g.
**1** see our earlier discussion here: https://gist.github.com/florianverhein/b644f0e2ae2edadf94a9 (I ended up solving that with a `Process[Task,A] => Iterator[A]`)
**2** https://spark.apache.org/docs/1.2.0/api/scala/index.html#org.apache.spark.rdd.RDD
`mapPartitions[U](f: (Iterator[T]) ⇒ Iterator[U], preservesPartitioning: Boolean = false)(implicit arg0: ClassTag[U]): RDD[U]` (there's similar stuff in map reduce frameworks)

The underlying requirement for **1** is to be able to drive the `Process` externally (i.e. there really shouldn't be a need for another thread and a blocking queue to integrate with other things). An interface that supports pulling values like e.g. `next : Option[A]` and `close : Unit` is fine (so just like `InputStream` but for all types), if that feels 'cleaner'. That's easy to turn into an `Iterator[A]` if necessary via (ugly!) lookahead and cache.

**Comment by pchlupacek** [comment]
What will happen with resources that will be in Process[Task,O]? How they will be sent over wire? On one hand iterator is lazy, but does it in spark open any resources or eventually close them? Does the Spark have any resource-safe api? Maybe we can easily hook to that?

**Comment by florianverhein** [comment]
Good questions @pchlupacek 
- Process should never need to be sent over the wire - they are instantiated on the worker nodes so all resources will be local there (note that if a user tries to do something silly, like instantiating them on the driver and referencing them in a closure, it will just result in a serialization exception as the Process isn't serialisable - I've checked this)
- I think you're asking about how resource closing would be handled in **1**. The iterator should close all resources in the process when it gets to the end (the iterator will be completely consumed in my use cases). If the iterator is not completely consumed (e.g. someone uses this interface for another use case), then the user is responsible for calling close themselves (i.e. the `() => Unit`)
- Spark does not have a resource safe API that I'm aware of. Also note that Spark provides java and python APIs for all(?) its functionality.

**Comment by djspiewak** [comment]
@pchlupacek One of the things I was thinking of here was that perhaps we should add a general tool for "controlled unsafe stepping".  Something higher level than `step` but more controlled than `toTask`.  The fundamental problem with `toTask` was that you couldn't really abort early, and the API itself was not referentially transparent.  The problem with `step` is that you basically need to know the `Process` algebra inside and out in order to make heads or tails of its output.

I'm generally thinking of something like this:

```scala
object unsafe {
  def step[F[_], A](p: Process[F, A]): Stepper[F, A]
}

trait Stepper[F[_], A] {
  def next: OptionT[F, A]
  def close: F[Unit]
}
```

We could also make `F[_]` concretely equal to `Task` if that makes more sense.  Obviously, there's nothing *safe* about this API, but it's *safer* than `toTask` and easier to use than `step`.

Another API option which would be *truly safe* would be to provide a function which derives an enumerator for `Process` (the iteratee-style enumerator).  This would probably of limited usefulness though, since any use case where iteratees are practical would probably also support streams with less hassle.  The `unsafe` API signatures are intended specifically to support use-cases where external constraints (i.e. frameworks) outright *prevent* more principled approaches.

**Comment by florianverhein** [comment]
@djspiewak no worries, just checking before attempting it :) 

I did **2** as well as a context-less version of **1**, i.e. `Process[Nothing,A] => Iterator[A]` - since this turns out to be useful too. I expect there are better ways, but here's what I came up with:
https://github.com/arkig/spream/blob/master/src/main/scala/spream/stream/Conversions.scala

If you're interested, here's an integration test that demonstrates how these can be used to integrate spark and scalaz.streams once data is partitioned appropriately: https://github.com/arkig/spream/blob/master/src/test/scala/spream/IntegrationSuite.scala
In practice (i.e. non-testing), **1** would be used in place of the `Process[Nothing,A] => Iterator[A]` conversion that's used in the test to create the RDD via flatMap.

**Comment by etorreborre** [comment]
@djspiewak I'm interested in a sketch of the `Stepper` implementation. I am currently trying to create a library of "monadic folds" which can be composed to traverse different types of data streams, iterators, scalaz processes or any Foldable. When I'm working with Scalaz Processes I would like to be able to transform a `Sink[Task, T]` into an "effectful" fold looking like this:
```
type SinkM = FoldM[T, M, Unit]
trait FoldM[T, M, U] {
  type S 
  def start: M[U]
  def fold = (s: S, t: T) => S
  def end(s: S): M[U]
}
```
My current implementation of `fromSink(sink: scalaz.Sink[Task, T]): SinkM[T, Task]` is both ugly and wrong because I can't step through a sink in the `fold` function and close when I want in the `end` function. I think that having a `Stepper` API would greatly help me.

**Comment by djspiewak** [comment]
@etorreborre `Stepper` is pretty easy to implement for a `Process` specialized on `Task` by delegating to `stepAsync`.  This also gives you access to an interrupt function, which would be ignored by the type signature in question.  It would look something like this:

```scala
def step[A](p: Process[Task, A])(implicit S: Strategy): Stepper[Task, A] = new Stepper {

  @volatile
  var state: Process[Task, A] = p

  def next: OptionT[Task, Seq[A]] = {
    val step: Task[(Seq[A], Cont[Task, A])] = Task async { cb =>
      p stepAsync { either =>
        cb(either leftMap Terminated)
      }
    }

    for {
      either <- step.attempt.liftM[OptionT]
      (as, cont) <- OptionT(Task now either.toOption)

      _ <- (Task delay { state = cont.continue }).liftM[OptionT]
    } yield as
  }

  def close: Task[Unit] = state.kill.run
}
```

I'm cheating just a bit here, since I changed the signature of `step` to return chunks.  Hopefully it is clear how you could carry chunks along in the current state though and page them incrementally, I just didn't want to go through that tedium.  :-)

The nice thing about implementing on top of `stepAsync` is you could expand `Stepper` to `InterruptibleStepper` which has an `interrupt: Task[Unit]` that you can use to safely and instantly kill off the in-progress action, if applicable.  You would do this by capturing and saving off the return result from `stepAsync`, which the above implementation discards.

You *can* implement `Stepper` in a fashion which is general to any `F` which has a `Monad` and a `Catchable` instance, but you would lose the ability to get an interrupter even when `F` happens to be `Task`.

**Comment by etorreborre** [comment]
Thanks @djspiewak. I have one issue with this solution, it is actually more complex than what I need because I don't need an asynchronous stepping and I don't want to have to pass a `Strategy` object. I tried though to go through that route and that lead me to some deadlocking which I couldn't solve.

I think I'm going to try to simply use the `Process.step` method and pattern match on that to step through a sink until I can close it. But given the internal representation of Process that doesn't seem very easy either :-). Maybe I can find some inspiration in how `runFoldMap` is implemented and stick a variable in there?

**Comment by djspiewak** [comment]
@etorreborre Here's a general implementation:

```scala
def step[F[_]: Monad: Catchable, A](p: Process[F, A]): Stepper[F, A] = new Stepper[F, A] {
  var state = p

  def next: OptionT[F, Seq[A]] = state.step match {
    case Halt(_) => OptionT.none

    case Step(Emit(as), cont) => {
      state = cont.continue
      OptionT some as.point[F]
    }

    case Step(Await(req, rcv), cont) => {
      for {
        tail <- (req.attempt map { r => rcv(EarlyCause fromTaskResult r).run +: cont }).liftM[OptionT]
        _ = state = tail          // purity ftw!
        back <- step
      } yield back
    }
  }

  def close = {
    state = state.kill.drain
    lazy val drain: F[Unit] = step flatMapF { _ => step } getOrElse (())

    drain
  }
}
```

**Comment by etorreborre** [comment]
Thanks @djspiewak! I got it to work by specialising to `Task` (otherwise I had `this is a GADT skolem`) and changing 3 things
```
  def step[A](p: Process[Task, A]): Stepper[Task, A] = new Stepper[Task, A] {
    var state = p

    def next: OptionT[Task, Seq[A]] = state.step match {

      case Halt(_) => OptionT.none

      case Step(Emit(as: Seq[A]), cont) =>
        state = cont.continue
        // 1st change
        OptionT(as.point[Task] map some)

      case Step(Await(req: Task[_] @unchecked, rcv), cont) =>
        for {
          tail <- (req.attempt map { r => rcv(EarlyCause fromTaskResult r).run +: cont }).liftM[OptionT]
          _ = state = tail          // purity ftw!
          // 2nd change s/step/next
          back <- next
        } yield back
    }
    // 3rd change
    def close = 
      Task.suspend {
        Task.delay(state = state.kill) >>
        state.run
      }
  }
```

I have a question about my 3rd change. Why did you assume that it was necessary to "drain" `step` (which I assume was actually `next` but even if I change that the line doesn't compile)?

Also why did you write `state.kill.drain`? It looks to me that `kill` is already doing `drain`.

Anyway I'm glad because this version seems to be working really fine :sunglasses:.

**Comment by pchiusano** [comment]
I can think of a bunch of ways of doing this with the new design. My inclination would be to punt until after 0.9 is out. This could be (re)added in a point release, even, it does not require any new primitives.

**Comment by pchlupacek** [comment]
Is this still relevant for 1.0 release?

**Comment by SystemFw** [comment]
I think the feature is still relevant, yes. Whether we care enough or not is a different question, let's se what @mpilquist thinks I'd say

**Comment by mpilquist** [comment]
I'm okay with closing it. If folks still want it, they can reopen and we can discuss what it would look like with 1.0.

**Comment by Leonti** [comment]
I'm struggling with this issue at the moment - I need to serve a file in Finch and the way to do it is to use their `AsyncStream` class: http://finagle.github.io/finch/cookbook.html#serving-static-content which can be created from `InputStream`
I tried using `fs2.io.toInputStream`, but it seems impossible to get an `InputStream` which is not consumed yet, for example:
```
    val is2: InputStream = stream.through(fs2.io.toInputStream).compile.toList.map(_.head).unsafeRunSync()

    println(scala.io.Source.fromInputStream(is2).mkString)
```
will print an empty string. 
Same deal with http responses - by the time `AsyncStream` is returned to the http server it's already consumed, so the output is empty.

Would be nice to have something like `toInputStreamUnsafe` for integration with 3rd-party frameworks
