### ISSUE TITLE
Constructor for Wye with one input as Process1

### ISSUE THREAD

**Issue by ghost** [functional-streams-for-scala/fs2#355]
I can't seem to find a straightforward way to construct a Wye with one input bound, the result of which is a Process1 from the other input to the output. In other words, it'd be super-handy to be able to easily construct transducers from some Process that you want to relate to some other process with Wye's combinators.

**Comment by pchiusano** [comment]
@psnively Well, you could use [attachL/R](https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/wye.scala#L218), however you are restricted to providing a `Process1`  or a `Process0` (since `Process0 <: Process1`), you can't bind something effectful. If you want to bind something effectful, you can just curry the wye function: 

```Scala
def bindL[F[_],A,B,C](in: Process[F,A])(y: Wye[A,B,C]): Process[F,B] => Process[F,C] = 
  bs => in.wye(bs)(y)
```

Also, note that a `Wye[A,Any,B]` (the result of `attachR` if you provide a `Process0`) can just be cast to a `Process1[A,B]`--they have the same representation at runtime. We could probably add functions for that in `wye` that lets people drop an ignored branch, though no one has asked for it yet.

**Comment by psnively** [comment]
You didn't just use "cast" in a sentence unironically, did you?

**Comment by pchiusano** [comment]
@psnively Ha. Yes, I guess I did! All I was saying is that if you want to implement this function:

```Scala
def capR[A,B,C](p0: Process0[B])(y: Wye[A,B,C]): Process1[A,C]
```

The simplest implementation might involve a cast: `wye.detach1R(wye.attachR(p0)(y)).asInstanceOf[Process1[A,C]]` (I realized the `detach` is prob needed to convert any AwaitBoths to AwaitL), and this shouldn't generate any runtime errors... I think. That might be how I would implement it internal to scalaz-stream after doing some testing, but it is cheating / unsafe for user code... I'm not necessarily recommending it. :)

If you are too horrified by that, you could also implement it via manual stepping, but that's going to be annoying (and you might have to have some casts in there anyway because of Scala's poor GADT support) as well as less efficient. I am not really happy with the API we have for stepping a stream and it will probably change in a future release.

Just to give a bit more context on why the cast hack should work, the following subtyping relationships hold:

```Scala
Process0[C] <: Process1[A,C] <: Tee[A,B,C] <: Wye[A,B,C]
```

A `Wye[A,B,C]` that never asks for any values from the `B` branch is thus at runtime behaving like a `Process1[A,C]`. And calling `attachR` with a `Process0` should result in a `Wye` that never blocks on the `B` branch, since if it did it would have been fed a value or killed if no values remained. And the `detach` gets rid of any AwaitBoths.

**Comment by pchiusano** [comment]
This is addressed pretty nicely with the new design. A `Wye[F,A,B,C]` is just a function `(Stream[F,A], Stream[F,B]) => Stream[F,C]`, and `Process1[A,B]` is a `forall F . Stream[F,A] => Stream[F,B]`, so the operation is now just partial application! No special combinators needed. :)
