### ISSUE TITLE
Add stateful `Process1` example?

### ISSUE THREAD

**Issue by refried** [functional-streams-for-scala/fs2#419]
like the one described at
https://github.com/scalaz/scalaz-stream/blob/master/src/test/scala/scalaz/stream/examples/StartHere.scala#L96

(I would do it if I could.)

**Comment by fthomas** [comment]
I think you can! Many `Process1`s in `process1.scala` that are recursive or that have an inner `go` function are stateful. See `filterBy2` for example: on receiving input elements it updates its internal state (the predicate `g: I => Boolean` parameter of the `go` function). If `g` evaluates to `true` it is changed, otherwise it is passed unchanged to the next `receive1` call.

**Comment by mpilquist** [comment]
I think the user guide's example of `take` means this can be closed?
