### ISSUE TITLE
 Appending pure stream to `F` stream yields in error

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#624]
Seems the pure type don't fit yet correctly :
 
```scala

scala> val s1:Stream[Task,String] = Stream("A","B")
// s1: fs2.Stream[fs2.util.Task,String] = fs2.Stream$$anon$1@62cff145

scala> val s2:Stream[Pure,String] = Stream("C","D")
// s2: fs2.Stream[fs2.Pure,String] = fs2.Stream$$anon$1@2d639a64

scala> s1 ++ s2
//<console>:24: error: could not find implicit value for parameter S: fs2.util.Sub1[fs2.util.Task,fs2.Pure]

```

**Comment by mpilquist** [comment]
I don't think there's any way to make the current scheme (based on `Sub1`) support this example. The problem here is that `++` is defined like this:
```
private[fs2] trait StreamOps[+F[_],+A] extends StreamPipeOps[F,A] with StreamPipe2Ops[F,A] {
  self: Stream[F,A] =>

  def ++[F2[_],B>:A](p2: => Stream[F2,B])(implicit R: RealSupertype[A,B], S: Sub1[F,F2]): Stream[F2,B] = ???
```
In this example, `F=Task, A=String, F2=Pure, B=String`. So the compiler looks for a `Sub1[Task,Pure]` instance and rightfully can't find one because `Task` can not be case to `Pure`. Instead, we want the compiler to insert a call to `s2.covary[Task]` but I don't think we'll be able to convince it to do that.

So we have a few options...

(1) Recommend the use of either type ascription or covary in this case. E.g., these both work:
```
  val d4 = Stream.eval(Task.now(4)) ++ Stream(1,2,3).pure.covary[Task]
  val d5 = Stream.eval(Task.now(4)) ++ (Stream(1,2,3).pure: Stream[Task, Int])
```
(2) Instead of using `Sub1[F,F2]`, we could create a witness like `trait Lub1[F[_], G[_]] { type Lub[_] }` and then define append like this:
```
  def ++[F2[_],B>:A](p2: => Stream[F2,B])(implicit R: RealSupertype[A,B], L: Lub1[F,F2]): Stream[L.Lub,B] = ???
```
If we go with option (2), I'm pretty sure I can get rid of the need for special cases like `throughp` and the `pure` method on `Stream` using Miles's inferrable nothing trick.

Any interest in a prototype branch of (2)? /cc @pchiusano

**Comment by pchlupacek** [comment]
I also thought about this Pure concept. And is there any reason why we don't type all pure pipes like Pipe[Pure,I,O]? I really liked in 0.8 the clear demarcation between pure and effect-full code, and is shame we sort of losing it now. I assume perhaps the `F` was there kept to fit in Sub1 constrains through the fs2._ code. But if any rework has to be done, I would like just to give it a thought ?

**Comment by mpilquist** [comment]
@pchlupacek I wouldn't say we are losing demarcation of pure pipes -- rather, we are explicitly stating that a pure pipe (i.e., a `foall F . Pipe[F, I, O]`) must not be effectful because the effect type is completely unconstrained. Hence, we are using parametricity to communicate that a pipe is pure.

**Comment by pchiusano** [comment]
I remember toying with the Lub idea but then somehow convinced myself it
wasn't needed. I think it might work. That example should not need
additional annotations or manual calls to covary.

What about just putting an implicit conversion from pure stream to any
other effectful stream in stream companion? Not sure if inference would
pick it up.

**Comment by mpilquist** [comment]
> What about just putting an implicit conversion from pure stream to any
other effectful stream in stream companion?

We have it already -- it doesn't get invoked in this case. That implicit conversion is why the type ascription example works.

https://github.com/functional-streams-for-scala/fs2/blob/series/0.9/core/src/main/scala/fs2/StreamDerived.scala#L232

**Comment by pchlupacek** [comment]
@mpilquist got you. Thats why this would compile with signatures where Pure is required right?

**Comment by pchiusano** [comment]
Ah okay. The Lub approach seems promising then.

We could also just tell people not to annotate with pure unless needed for
inference. But there are cases where Pure will still arise out of necessity.
