### ISSUE TITLE
Consider replacing Either[Throwable,A] with Try[A]

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#678]
Paul and I had discussed this a number of months ago but never came to a resolution. Currently, we use `Either[Throwable,A]` in lots of places, along with constructs like: `try Right(a) catch { case t: Throwable => Left(t) }`. By switching to `Try`, we'd only catch non-fatal exceptions, which may or may not be considered desirable. I lean towards using `Try` (I want a `NonFatal` exception to trigger application shutdown) but I'm eager to hear other opinions.

**Comment by djspiewak** [comment]
Stick with `Either` for the composability and add the following utility:

```scala
object Try {
  def apply[A](body: => A): Either[Throwable, A] =
    try Right(body) catch { case NonFatal(t) => Left(t) }
}
```

**Comment by mpilquist** [comment]
Is that just to avoid the various exception handlers built-in to `scala.util.Try`? And just to verify, you are in favor of only catching non-fatals, right?

**Comment by pchiusano** [comment]
I was just taking a look at NonFatal, and it includes ControlThrowable,
which is an exception type used for control flow I guess? We definitely
need to catch that - if we didn't then some random library using that
exception for control flow could subvert resource safety of FS2 not to
mention deadlock the computation. Consider

eval(Task.delay { throw new ControlThrowable() }).onFinalize(blah)

There can't safely be anything above Stream in terms of control flow.

NotFatal also doesn't catch InterruptedException, which we need to catch
for the same reasons. (Wasn't the whole point of InterruptedException to
give the thread a chance to cleanup resources before exiting?)

If we want to introduce our own version of `NonFatal` that only excludes
errors that should shut down the VM and use that everywhere internally, I'd
be cool with that. It does not seem worth it to introduce a separate `Try`
type (which will be different than the one in the standard library, and one
more thing to learn) just to get this behavior.

We should also make sure that any thread factories we use have a sensible
uncaught exception handler that logs all errors (and maybe even logs fatal
errors with a scarier message).

**Comment by djspiewak** [comment]
I'm in favor of only catching non-fatals.  Catching and attempting to recover from any of the fatal throwables is very non-deterministic behavior.  Normally, SOE is pretty safe to catch and recover, but things like OOME and friends are *really* not safe.  I've actually had bugs in production where the JVM has entered a non-deterministic state (and continued running!) after catching and swallowing OOME by accident.  If a fatal throwable is raised, the JVM should go down.  Full stop.

The recommendation to avoid `Try` is actually just because it's effectively an `Either` that is specialized on `Throwable`, but with a *different* nominal type.  Moving between the two is a pain (even more of a pain than `Either` itself), and there's no reason to do that.

@pchiusano I don't have an objection to rolling your own `NonFatal`.  You should definitely have special semantics for `InterruptedException`.

It is worth noting though that catching `ControlThrowable` will do some interesting things with primitive language functions.  For example:

```scala
str map { x =>
  if (x > 0) return x

  x + 1
}
```

Actually valid Scala.  Catching `ControlThrowable` will result in this not behaving appropriately.  But then again, what is "appropriate" in this case?  Probably better to just tell users "don't do that" and catch the `ControlThrowable`.

**Comment by pchlupacek** [comment]
I came with same idea while ago (#456). The arguments at that time were that try is catching some exceptions and some not. I still believe this is valid point.  

However I dislike the fact of having Either, because it doesn't rock in term of composability (all these projections and so on). And still the Throwable part is redundant, as it won't bring any relevant type to us. 

I would perhaps suggest to bring some utility types, syntaxes etc on top of Either so we stick to Either, but where it is hard to work with it, we simply import syntax or helpers.

**Comment by mpilquist** [comment]
I'm on board with a `fs2.util.NonFatal` that catches more than `scala.util.control.NonFatal`. I'm pretty neutral on introducing a type alias for `Attempt[A] = Either[Throwable,A]`. One one hand, we'd be introducing another new concept but on the other hand, we'd have a place to put syntax. If there are no strong objections to the type alias, I'll put a PR together.

**Comment by pchiusano** [comment]
No objections to introducing the type alias and an fs2.util.NonFatal

**Comment by pchlupacek** [comment]
I get the argument to shutdown on encountering OOM, but this may be handled with `-XX:OnOutOfMemoryError="<cmd args>; <cmd args>"`. I am still not bought on idea of handling some exceptions and some not. What are the other exceptions bringing the JVM to "unstable" state?
