### ISSUE TITLE
fs2._ and fs2.Stream._ conflicts on Pull

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#694]
Is this really intended ? Effectively if you are using Pulls, one cannot have these two underscore imports in single file. I would opt for removing the Stream.Pull if possible, or make it private to Stream object

**Comment by mpilquist** [comment]
I don't think we can remove the one from Stream (nor make it private). It is defined as an abstract type member in [Streams](core/shared/src/main/scala/fs2/Streams.scala). Perhaps we should remove `Streams` entirely though? It defines the signatures of the primitive operations on something that's stream-like, but I don't think we'll ever implement it.

Note that we can't just replace the `Pull`/`Handle` abstract type members with concrete references because the concrete `Pull`/`Handle` types reference `fs2.Stream`, not the stream type param on `Streams`. Also, `Streams` currently references `ScopedFuture`, which is bound to the concrete `Stream` and `Pull` types -- i.e., `Streams` is already not as general as it claims to be.

@pchiusano Thoughts?

**Comment by pchiusano** [comment]
Am fine with getting rid of Streams. It was helpful during design phase but
not needed anymore. If we want we can document what the core primitives are
in other ways (perhaps another doc linked from guide).

**Comment by mpilquist** [comment]
I removed `Streams` and `Pulls` on a branch in my fork: https://github.com/mpilquist/fs2/commit/5c2971878014e0c8c8cd2c07369c34963385b726

I'll open a PR later today hopefully. There's more cleanup I'd like to do now that we don't have `Streams` and `Pulls` though -- specifically, this lets us get rid of the `Derived` traits, which then lets us use value classes for syntax, resulting in a small performance boost.
