### ISSUE TITLE
Introduce toInputStream

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#725]
Some Java API require InputStream as source of data w/o eventually providing any other way how to feed data. Eventhough we have already simple ways to read from InputStream, this intends to create a way to convert Stream of Bytes to inputStream consumable with JavaAPI.

The basic idea is : 

```scala

val source : Stream[F,Byte] = ???

// Input Stream is closed when the source finsihes. Source is killed when InputStream terminates
val is:Stream[F,InputStream] = source.toInputStream

```

**Comment by mpilquist** [comment]
:+1: to supporting conversion to an input stream. This comes up frequently enough that it's worth having in the library. 

Some miscellaneous thoughts:
 - Should `unsafe` be somewhere in the name or, since we are working with input streams, unsafety is implied?
 - Should live in the `io` package, which means we'd either need to enrich the `toInputStream` on to `Stream` or do something like `source.through(io.toInputStream)`
 - Should we address this at the same time as https://github.com/functional-streams-for-scala/fs2/issues/323?.
 - Timing wise, is this post 0.9 final?

**Comment by pchlupacek** [comment]
@mpilquist I will have draft implementation today. I really need it :-) I am implementing this as an pipe. Hence the Stream[F,InputStream] I think it is not inherently unsafe, at least my implementation would be safe from the resource perspective. Where you need however take care is the blocking and effectful nature of inputStream#read et all, but not sure how to guard that. I think there we have to leave with knowledge of user to know what can go wrong with input stream. 

as regards #323 I was sort of looking on signature in runStep or something like that. I am not yet able to generalize that properly, but so far using synchronous queue or Ref seems to work fine.
