### ISSUE TITLE
Stream loses data in one case in onError

### ISSUE THREAD

**Issue by dwhitney** [functional-streams-for-scala/fs2#760]
I've added some test cases in a fork that show this: 
https://github.com/dwhitney/fs2/blob/series/1.0/core/jvm/src/test/scala/fs2/StreamSpec.scala#L79
https://github.com/dwhitney/fs2/blob/series/1.0/core/jvm/src/test/scala/fs2/StreamSpec.scala#L89

Basically, the following code fails:
```
val stream = Stream.emits(List(1, 2, 3, 4)).map{ i => 
        if(i == 3) throw new Exception("no 3s!")
        else i
      }.onError(_ => Stream.emit(100))
assert (stream.toList == List(1, 2, 100)) 
```
but what should be identical in behavior does not:
```
val stream = (Stream.emits(List(1, 2)) ++ Stream(3, 4)).map{ i => 
        if(i == 3) throw new Exception("no 3s!")
        else i
      }.onError(_ => Stream.emit(100))
assert (stream.toList == List(1, 2, 100)) 
```

**Comment by pchiusano** [comment]
This is as designed. If an exception occurs midway through mapping a single
chunk, none of the elements in the chunk are emitted. If you don't want
this behavior, you can explicitly catch the errors in the f passed to map
and use Either/Option. Or you can chunk your stream differently, or use
flatMap. My feeling is that errors in pure code like this are very bad
style.

But, I was thinking about whether this design is 'correct' and whether we
should try to change it. We should discuss. A couple points:

* The Stream interpreter is just calling Chunk.map, so it can't really
detect when the function throws. I don't see an easy way to change this.
* There are a lot of ways one can observe the chunk structure of the
stream, by design, and different chunkings can behave differently.
* Laws? What laws do we want to hold?

**Comment by mpilquist** [comment]
This is caused by `map` on `Stream` being implemented in terms of `mapChunks`. Specifically, `map(f) = mapChunks(_ map f)`. To fix, we'd need something like `attemptMap` on `Chunk`:

```scala
def attemptMap(f: A => B): (Option[Throwable], Chunk[B])
```

We'd then need to use `attemptMap` instead of `map` and find a way to emit the chunk followed by pushing the failure if defined.

@pchiusano Any thoughts?

**Comment by mpilquist** [comment]
Also, note that `map(f) = flatMap(f andThen emit)` does not have the problem.

**Comment by pchiusano** [comment]
Proposed fix of attemptMap makes sense though not sure I endorse that.
Splitting up chunks in a way the user has not explicitly requested seems
weird to me.

The flatMap version produces a different chunk structure and isn't the same
thing as map, except up to some equivalence where chunk structure is
ignored.

**Comment by pchiusano** [comment]
Just noticed that the laws stated for stream are pretty sloppy in that they
don't state what is meant by ==. We should definitely make it more clear
(both to ourselves and to users) that equalities are like modulo chunk
structure. If you start observing chunk structure many of the given
equalities don't hold.

**Comment by adelbertc** [comment]
https://github.com/functional-streams-for-scala/fs2/issues/750 :D

**Comment by mpilquist** [comment]
@pchiusano My comment about `flatMap(f andThen emit)` was not a suggestion for a fix but rather a note that identity is broken. It would be nice if `map(f) == flatMap(f andThen emit)` in presence of exceptions thrown from `f`. I suppose we could argue that `Stream` is not a lawful monad in presence of exceptions from pure functions, which is probably a reasonable position.

**Comment by pchiusano** [comment]
Oh ya I didn't think you meant that. Let's have a pow wow when you are back
in town.

Consider:
s.flatMap(emit).chunks.map(_=>1).sum vs
s.chunks.map(_=>1).sum

Also consider the law about associativity of append.

The laws don't hold when you start observing the chunk structure of the
stream. onError as implemented can do that, but so can just an ordinary
pure Pull that works on chunks.

The way to salvage this is just to more clearly state the notion of
equality used in the laws - it's a more limited notion.

**Comment by dwhitney** [comment]
the caller of a method that returns a stream would have to know implementation details to understand how to properly handle this, right? That seems less than ideal. Could you not simply keep track of the part of a chunk that has been properly "processed" and make sure that is emitted when an error is encountered -- in addition to whatever is passed to `onError`

**Comment by djspiewak** [comment]
@dwhitney `Chunk#map` would need to be changed to produce type `(Chunk[B], Option[Throwable])`, not impossible, but tremendously annoying.  I'm basically of the opinion that all reasonability and caller/callee guarantees go out the window once you start throwing raw exceptions.  There's just no way to make it sane in general.  We can probably squash this one case, but there are a dozen other similar cases that aren't so easily addressed.

**Comment by pchiusano** [comment]
Hey, @mpilquist and I were just chatting about this. Decision was we aren't going to change the behavior (I'll explain reasons in detail soon) and will instead just clarify the laws for Stream and add appropriate caveats. We get that this might violate intuitions, but there are actually good arguments in both directions for that.

Will update this issue with link to PR and some discussion.

**Comment by dwhitney** [comment]
as adjustments are made, I'd like to point out that this is a great opportunity to incorporate that `blowChunks` method @bvenners made at SBTB ;)

**Comment by pchiusano** [comment]
So, here's the reasoning for not changing this, based on discussion with @mpilquist (feel free to pipe in)

* It's not clear to me that either choice is more intuitive; one could argue that the user will be expecting `map` to preserve chunk structure in all cases.
* As @djspiewak pointed out, there are lots of other functions where one could argue for such treatment (think `filter`, `scan`, and lots of others). It's a can of worms and feels pretty ad hoc.
* The laws don't really have anything to say about this. It is already true the `map` as implemented differs from `map` derived from the monad, since the monad-derived map will produce singleton chunks. (I noted this in #769)
* Exceptions in pure code are really strongly discouraged. They shouldn't compromise resource safety, but we won't go to great lengths to catch these exceptions at any granularity below an entire chunk.

The current behavior (of only catching exceptions at level of entire chunks) is simple to understand, and if people want more fine grained handling, they should do that using the functions they pass to `map`, etc.
