### ISSUE TITLE
RFE: Ref/Signal modifyF

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#888]
```scala
def modifyF[B](f: A => F[(A, B)]): F[(Change[A], B)]
```

This would be useful on both `Ref` and on `mutable.Signal`.  It's similar in principle to `modify2`, but allows an effect context to be threaded through.  This makes it possible to evaluate `StateT` through a `Signal` (with retry), which is sometimes very nice.

Also, this is somewhat trivial to implement.  Simply `flatMap` the results of the `f` inside `tryModify2`.

**Comment by mpilquist** [comment]
No objections here. PR?

**Comment by pchlupacek** [comment]
@djspiewak  I assume this shall acquire lock, eval `F` and release lock in case `F` evaluates or fails right? That would be welcome. In fact I would sugest to have these two : 
```scala 
def modifyF[B](f: A => F[A]]): F[Change[A]] = ???
def modify2F[B](f: A => F[(A, B)]): F[(Change[A], B)]
``` 
to have them consistent with current `modify` naming

**Comment by wedens** [comment]
In haskell effectful modify for `MVar` is implemented like this (with removed irrelevant to scala things):
```haskell
modifyMVar :: MVar a -> (a -> IO (a,b)) -> IO b
modifyMVar m io = do
    a <- takeMVar m
    (a', b) <- io a `onException` putMVar m a
    putMVar m a'
    return b
```
The missing thing in `Ref` is something like `takeMVar` that works like `get` but also unsets `Ref`. 

`scalaz.concurrent.MVar` does it similarly to haskell `MVar`.

**Comment by SystemFw** [comment]
So, I've spent some time deep diving into the internals of fs2 async, and I'm convinced that the fact a `Ref` can't be unset is a feature. 
The fact that most compound operations on `MVar` involve `takeMVar` is a weak point, since it can cause other threads to needlessly block: in fact, `readMVar` is no longer implemented as "take then put" for exactly this reason, and it now appears to be a native operation.
Conversely, it's easy to implement something like `takeMVar` in terms of `Ref`: just have a `Ref[F, (Option[A], Vector[Ref[F,A]])]`, where the `Vector` holds uninitialised `Ref`s for the readers which are queueing on `None` (similarly to what it's done in `Queue`).

Now, using `Ref`s `modify` semantics to implement `modifyF` does raise some interesting questions about the semantics of `modifyF`, especially with regards to how many times the effect is evaluated.
Off the top of my head (they are both untested), I can imagine two different implementations - using the simpler  `modifyF(f: A => F[A]): F[Change[A]]` as an example.

- This implementation applies `f` to the most recent contents of the `Ref`, but it will reevaluate the effect a nondeterministic amount of times, so it's perhaps only good for idempotent effects.
```scala
def modifyF[B](f: A => F[A]): F[(Change[A]] =
    access.flatMap { case (previous, set) =>
      f(previous).flatMap { now =>
        set(Right(now)).flatMap { succeeded =>
          if(succeeded) F.pure(Change(previous, now))
          else modifyF(f)
        }
      }
    }
```
- This implementation only runs the effect once, but the drawback is that by the time the new result is set, the initial result might have changed, so I'm not sure whether the returned `Change` has the correct semantics wrt `previous`. The same could be said for the classical `MVar` implementation though.
```scala
  def modifyF[B](f: A => F[A]): F[Change[A]] = 
    get.flatMap { value =>
      f(value).flatMap { result =>
        setSyncPure(result).as(Change(value, result))
      }
    }
```

Note that I haven't thought about exceptions yet, but obviously that's another important concern. 
WDYT?

**Comment by mpilquist** [comment]
I think the first implementation of `modifyF` is fine, along with something like the following:

```scala
def tryModifyF(f: A => F[A]): F[Option[Change[A]]] =
  access.flatMap { case (previous, set) =>
    f(previous).flatMap { now =>
      set(Right(now)).map { succeeded =>
        if(succeeded) Some(Change(previous, now))
        else None
      }
    }
  }
```

**Comment by pchlupacek** [comment]
@mpilquist @SystemFw I am not sure that the implementations satisfy the original idea, i.e that during the evaluation of `f` there is lock imposed on the ref, so no-one can actually modify the ref. Obviously the first implementation is ok, but hence `f` is now wrapped in `F` we need guarantee that effect is run only once. Otherwise it is not that much value over an pure implementation which we currently have in place , except a  bit of syntactic sugar. 

Having said that, I am not sure if this can be implemented without touching internals of `Ref` more deeply. One of the idea I had was to implement internals of `Ref` with `Eval`, so it will be something like `Ref[Eval[A]]` internally, and use Eval to guard eval-once behaviour of `F`.  But not sure how that could go.

**Comment by SystemFw** [comment]
I think this can (only?) be implemented with a new message type in the `Actor`, that runs the effects only when it wins a race. 
The other thing that puzzled me is that `Ref` can also be set with an `F[A]` that fails, and `set` will succeed, and the next `get` will fail. `modifyF` could have similar semantics, but they were surprising to me.

**Comment by mpilquist** [comment]
Moving this to post 0.10

**Comment by pchlupacek** [comment]
Hence the Ref lives now in cats.effects, and signal sort of replicates ref's syntax, what do to here ?

**Comment by SystemFw** [comment]
Actually, after a long thought, it isn't possible to do this with `Ref` or `MVar` at all, you need something like `Semaphore` or implement your logic in a different way that doesn't' require this guarantee (I can provide an example of this).
Therefore this should be closed.
