### ISSUE TITLE
Make Actor public

### ISSUE THREAD

**Issue by cannedprimates** [functional-streams-for-scala/fs2#890]
I've been migrating from scalaz to fs2 and cats-effect and Actor is one of the few dependencies I haven't been able to replace.
Please consider moving it to e.g. async.mutable or even just remove the private[fs2].

cheers!

**Comment by pchlupacek** [comment]
@cannedprimates There is in fact reason why we don't expose Actor directly. Since fs2 0.9 it has been replaced by Async.Ref, that shall give you in fact much more safe and flexible way for any scenario you have been using Actor. 

If you will have any specific trouble in migrating Actor based code, please feel free to shot any questions. Good idea to start may be comparing the fs2 async implementations aginst ones in scalaz.stream.

**Comment by cannedprimates** [comment]
will look into async.ref, thanks for the pointer!

**Comment by mpilquist** [comment]
Closing this for now. I agree that we we should recommend use of `Ref` and keep `Actor` as an implementation detail.
