### ISSUE TITLE
turn stream of values into stream of tuples

### ISSUE THREAD

**Issue by andykais** [functional-streams-for-scala/fs2#935]
Hi, I have a stream of values that I want to group together into adjacent tuples

`groupBy` almost seems like what I am looking for, however I just see one example in the codebase
```scala
scala> import cats.implicits._
scala> Stream("Hello", "Hi", "Greetings", "Hey").groupBy(_.head).toList
res0: List[(Char,Vector[String])] = List((H,Vector(Hello, Hi)), (G,Vector(Greetings)), (H,Vector(Hey)))
```

essentially I want to do something like
```scala
scala> Stream("a", "b", "c", "d").groupBy(/*unsure what goes in here*/).toList
res1: List((a,b), (b,c), (c,d))
```
is something like this accomplishable?

**Comment by SystemFw** [comment]
You can use `zipWithNext`
```scala
  def b = Stream("a", "b", "c", "d").zipWithNext.toVector
 res0: Vector[(String, Option[String])] = Vector((a,Some(b)), (b,Some(c)), (c,Some(d)), (d,None))
````

Note that the second val is wrapped in Option because you can't know in advance when the stream is going to end, but you can further modify the Stream to get what you want:

```scala
  def b = Stream("a", "b", "c", "d").zipWithNext.collect { case (x, Some(y)) => x -> y}.toVector
  res0: Vector[(String, String)] = Vector((a,b), (b,c), (c,d))
```

In the future, please ask this kind of questions on the gitter channel (https://gitter.im/functional-streams-for-scala/fs2) :)

**Comment by andykais** [comment]
thank you, and apologies I will refer to the gitter in the future

**Comment by SystemFw** [comment]
No apology needed :)
Gitter will get you quicker answers (which often spark interesting conversations) and allows us to keep the issue tracker focused on bugs and features requests. See you there ;)

**Comment by zoraida** [comment]
Hi, is this solution parallelizable? I mean, since a given element of the stream needs the next result, how can be this solution parellizable if it is not by running twice the elements?

**Comment by SystemFw** [comment]
I'm not sure how you would parallelise this. It seems like an intrinsically sequential operation since it's not a List, the elements are emitted as you go. Also, grouping into tuples is cheap enough that I doubt you'll get any benefits (and perhaps you'd get a slow down) if you do it asyncly.

Obviously, you could parallelise whatever operation you do _on_ the tuples (e.g. an http call)

**Comment by zoraida** [comment]
Thanks Fabio! It did not make sense to me but I wanted to be sure.
